Nuvoton-Israel/openbmc

meta-quanta/meta-runbmc-nuvoton/recipes-phosphor/console/files/obmc-console.conf
The parameters are specified in obmc-console related settings.
It's updated according to https://gerrit.openbmc-project.xyz/c/openbmc/meta-quanta/+/25269.
=> meta-quanta: runbmc-nuvoton: console: configure SOL parameters

meta-nuvoton/recipes-kernel/linux/linux-nuvoton/0001-driver-ncsi-replace-del-timer-sync.patch, meta-nuvoton/recipes-kernel/linux/linux-nuvoton_git.bb
1. replace del_timer_sync() with del_timer()
=> meta-nuvoton: linux-nuvoton: ncsi: patchs updated

meta-phosphor/nuvoton-layer/recipes-phosphor/ipmi/phosphor-ipmi-flash/phosphor-ipmi-flash-bios-update.service
To avoid software manager get JobRemoved signal just started
BIOS update service, change service type to oneshot
=> Change IPMI flash BIOS update service type to oneshot

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/logging/olympus-nuvoton-boot-error-native.bb, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/logging/olympus-nuvoton-boot-error/Boot.metadata.yaml
update watchdog metadata
Add watchdog error metadata for sel logger can get watchdog information
from D-Bus signal
=> meta-quanta: olympus-nuvoton: olympus-nuvoton-boot-error-native

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/debug/olympus-nuvoton-debug-collector/set_olympus_dbus_error.patch
1. move set SEL log part to phosphor-sel-logger
2. get watchdog information from journal if watchdog D-bus object is
gone
3. report watchdog event with metadata for pass information to phosphor
sel logger
=> meta-quanta: olympus-nuvoton: debug-collector: move SEL part

meta-quanta/meta-olympus-nuvoton/recipes-extended/pam/libpam/pam_succeed_if_support_ldap_user_login.patch, meta-quanta/meta-olympus-nuvoton/recipes-extended/pam/libpam_%.bbappend
1. The pam_succeed_if.so checks if the user belongs to the redfish group.
2. Add webui login support for the LDAP user.
3. The redfish group in the LDAP server needs to include the user as a member.
=> meta-quanta: olympus-nuvoton: libpam support LDAP user login

meta-quanta/meta-olympus-nuvoton/recipes-olympus-nuvoton/mac-address/files/config.txt, meta-quanta/meta-olympus-nuvoton/recipes-olympus-nuvoton/mac-address/files/mac-address.service, meta-quanta/meta-olympus-nuvoton/recipes-olympus-nuvoton/mac-address/mac-address.bb, meta-quanta/meta-olympus-nuvoton/recipes-olympus-nuvoton/packagegroups/packagegroup-olympus-nuvoton-apps.bb
1. Set eth1 mac address from bmc fru
2. This package is using to replace first-boot-set-mac
=> meta-quanta: olympus-nuvoton: add mac-address package

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/settings/phosphor-settings-manager_%.bbappend
1. Referenced link: https://gerrit.openbmc-project.xyz/c/openbmc/meta-quanta/+/33641
Signed-off-by: Joseph Liu <kwliu@nuvoton.com>
=> meta-quanta: olympus-nuvoton: settings: enable sol by default

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/ipmi/phosphor-ipmi-kcs/99-ipmi-kcs.rules.rules
1. The referenced link is "https://gerrit.openbmc-project.xyz/c/openbmc/meta-quanta/+/33798".
=> meta-quanta: olympus-nuvoton: ipmi: add kcs device

meta-nuvoton/recipes-bsp/images/npcm7xx-ddr4si-test_1.0.0.bb, meta-nuvoton/recipes-bsp/images/npcm7xx-gfx-test_1.0.0.bb, meta-nuvoton/recipes-bsp/images/npcm7xx-igps-native_02.01.12.bb, meta-nuvoton/recipes-bsp/images/npcm7xx-igps/0002-MFG-Test.patch, meta-phosphor/classes/image_types_phosphor_nuvoton.bbclass
Note: 1. concatenate BB and uboot image and Test images
as mergedBootBlockAndUbootAndTests.bin
2. MTest only has header for recording test result
3. each header is 0x100 in bytes
=> meta-nuvoton: recipes-bsp: images: Support MFG Test

meta-nuvoton/recipes-kernel/linux/linux-nuvoton_git.bb
Fix image update fail via bmcweb cause by Uboot partition size
is not enough.
=> meta-nuvoton: linux-nuvoton: bump srcrev 30714f6...317aef8

meta-nuvoton/recipes-nuvoton/ipmi/nuvoton-ipmi-oem_git.bb
1. Add the recipe for Nuvoton IPMI OEM command library
=> meta-nuvoton: nuvoton: add Nuvoton IPMI OEM command library

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/dbus/phosphor-dbus-interfaces/0001-Software-Add-MCU-VersionPurpose.patch, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/dbus/phosphor-dbus-interfaces_%.bbappend, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/flash/phosphor-software-manager/obmc-flash-host-bios@.service, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/flash/phosphor-software-manager_%.bbappend
move software manager to Nuvoton customized for BUV
=> meta-evb: meta-evb-nuvoton: meta-buv-runbmc: phosphor-software-manager

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-kernel/linux/linux-nuvoton/arch/arm/boot/dts/nuvoton-npcm750-buv-runbmc.dts
disalbe udc9 in DTS for enable USB host
=> meta-buv-runbmc: Enable USB host function

meta-nuvoton/conf/machine/include/npcm8xx.inc, meta-phosphor/classes/fitimage_nuvoton_npcm8xx.bbclass
1. a workaround to let u-boot examine fdt header.
=> meta-nuvoton: conf: align fdt binary in openbmc fitimage

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/sensors/dbus-sensors_%.bbappend
Update phosphor-ipmi-host version and remove dbus sensor patches
to fix BUV board build break
Note!!
Only fix build break, distro buv-entity a lot of functions may not work now...
=> meta-buv-runbmc: fix build break

meta-nuvoton/recipes-phosphor/webui/webui-vue/0002-Add-Nuvoton-MCU-firmware-support.patch, meta-nuvoton/recipes-phosphor/webui/webui-vue/0003-DEMO-Add-reboot-cause-support.patch, meta-nuvoton/recipes-phosphor/webui/webui-vue_%.bbappend
1. Add Nuvoton MCU firmware support
2. Add show reboot casue support for demo purpose,
this feature only work on xyz API, not redfish
=> meta-nuvoton: webui-vue: Porting features from phosphor-webui

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/packagegroups/packagegroup-obmc-apps.bbappend
Fix fru-device package cannot remove in normal distro.
The IMAGE_FEATURES_remove not take effect in bbappend
=> meta-quanta: olympus-nuvoton: packagegroup-obmc-apps

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/configuration/entity-manager/olympus-reload-sensor-off.service, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/configuration/entity-manager/olympus-reload-sensor-on.service, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/configuration/entity-manager/olympus-reload-sensor.sh, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/configuration/entity-manager/xyz.openbmc_project.EntityManager.service, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/configuration/entity-manager_%.bbappend, meta-quanta/meta-olympus-nuvoton/recipes-x86/chassis/x86-power-control_%.bbappend
Porting reload sensor process from hwmon
1. sync entity manager service from upstream
2. revert x86 power control change for enable process for entity manager
3. add reload-sensor service files
Issue:
ipmi sdr list command execute fail if BMC boot before host PC
Root Cause:
pmbus driver may not update attribute rated_max after probe, and
ipmid will access this attribute by PSU sensor dbus property Max_Value
for calculate sensor value to match ipmi sensor data format.
see IPMI v2 spec 36.1 Linear and Linearized Sensors
Solution:
remove sensors on bus 6 which monitor host power while host power off,
and add it back when host power on.
Test:
run ipmitool sdr list, host power on/off, BMC reset
=> meta-quanta: meta-olympus-nuvoton: entity-manager: porting reload sensor

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/watchdog/phosphor-watchdog/0001-Customize-phosphor-watchdog-for-Intel-platforms.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/watchdog/phosphor-watchdog/phosphor-watchdog.service
target error
1. update Intel patch to internal 0.57
ref: https://github.com/Intel-BMC/openbmc/tree/intel/meta-openbmc-mods/meta-common/recipes-phosphor/watchdog/phosphor-watchdog
2. change hardreset target to
xyz.openbmc_project.State.Host.Transition.ForceWarmReboot.
the x86-power-control does not support xyz.openbmc_project.State.Chassis.Transition.Reset
=> meta-quanta: meta-olympus-nuvoton: recipes-phosphor: fix start hardreset

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/ipmi/phosphor-ipmi-host/0001-add-watchdog-sensor-type.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend
Add sensor type watchdog for dbus-sdr SEL.
Note. the new version ipmid already update new sensor type, this patch should remove if update ipmid.
=> meta-quanta: meta-olympus-nuvoton: phosphor-ipmi-host: add sensor type

meta-quanta/meta-olympus-nuvoton/recipes-olympus-nuvoton/packagegroups/packagegroup-olympus-nuvoton-apps.bb, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/interfaces/bmcweb_%.bbappend
Summary:
1. Intel Crashdump v1.0.6
2. Crashdump Redfish new curl:
/redfish/v1/Systems/system/LogServices/Crashdump/Actions/LogService.CollectDiagnosticData
3. Crashdump Redfish new parameters:
DiagnosticDataType:"OEM" and "OEMDiagnosticDataType":"OnDemand" or "Telemetry"
4. New object path OnDemand:
/com/intel/crashdump/OnDemand and /com/intel/crashdump/Telemetry
5. SendRawPeci Redfish API didn't support anymore
Verify by DBus:
busctl call com.intel.crashdump /com/intel/crashdump/OnDemand
org.freedesktop.DBus.Properties Get ss "com.intel.crashdump" "Log"
Verify by Redfish:
curl -k -H "X-Auth-Token: $token" -X POST
https://${bmc}/redfish/v1/Systems/system/LogServices/Crashdump/Actions/
LogService.CollectDiagnosticData -d
'{"DiagnosticDataType":"OEM", "OEMDiagnosticDataType": "OnDemand"}' …
=> meta-quanta: olympus-nuvoton: enable Crashdump functionality

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/conf/machine/buv-runbmc.conf
update buv-runbmc machine configuration to avoid override by image_types_phosphor.bbclass
=> meta-evb: meta-buv-runbmc: update buv-runbmc configuration

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/configuration/entity-manager/F0B_BMC_BMC.json, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/configuration/entity-manager_%.bbappend, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/interfaces/bmcweb_%.bbappend, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/inventory/buv-runbmc-inventory-cleanup.bb, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/inventory/buv-runbmc-inventory-cleanup/inventory-cleanup.yaml, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/inventory/phosphor-inventory-manager/associations.json, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/inventory/phosphor-inventory-manager_%.bbappend, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/sensors/phosphor-hwmon_%.bbappend, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-x86/chassis/x86-power-control/power-config-host0.json
1. update entity manager recipe and configuration file
2. enable bmcweb old style xyz rest API
3. fix web UI cannot show any HW sensors by update inventory recipe
4. update hwmon recipe typo
5. update x86 power control configuration file to match new format
=> meta-evb: meta-buv-runbmc: fix services down after merge code

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ecc/phosphor-ecc/phosphor-ecc.service, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ecc/phosphor-ecc_%.bbappend
Note: execute ecc_main only when ecc is enabled
service file will check below edac path
/sys/devices/system/edac/mc
=> meta-evb-npcm845: phosphor-ecc: reload service file

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/flash/phosphor-software-manager/report_same_version.patch, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/flash/phosphor-software-manager_%.bbappend, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/flash/phosphor-software-manager/report_same_version.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/flash/phosphor-software-manager_%.bbappend
We should report version already exist error instead of do nothing,
and just wait for bmcweb timeout (600 seconds).
If we can report the exist error, the bmcweb will return http 400
when recive error report. No need to wait for firmware update timer
timeout.
=> phosphor-software-manager: report version alreay exist error

meta-nuvoton/recipes-bsp/u-boot/u-boot-emmc.inc
The wrong size setting will cause getting bad CRC32 when uboot load
environment settings from SPI flash.
=> meta-nuvoton: correct uboot env size

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/flash/phosphor-software-manager/obmc-flash-host-bios@.service, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/flash/phosphor-software-manager/obmc-flash-host-bios@.service
The BIOS update progress is not trigger reboot guard in software
manager, enable it before bios update and disable it after update
finished.
=> meta-quanta: meta-olympus-nuvoton: software-manager: enable reboot guard

meta-nuvoton/recipes-nuvoton/loadmcu/files/mcu-version.sh, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/fans/phosphor-pid-control/fan-boot-control.service
1. mcu version service: move version path to writable space
2. fan-boot-control: correct hwmon device
=> meta-quanta: meta-olympus-nuvoton: fix service startup errors

meta-quanta/meta-olympus-nuvoton/conf/bblayers.conf.sample, meta-quanta/meta-olympus-nuvoton/recipes-olympus-nuvoton/packagegroups/packagegroup-olympus-nuvoton-apps.bb
Missing change for commit 93ca686f6854d3e4e
1. package smbios-mdrv2 -> smbios-mdr
2. use the upstream intel oem ipmi need add intel layer back
=> meta-quanta: meta-olympus-nuvoton: fix pakage missing build break

meta-quanta/meta-olympus-nuvoton/recipes-core/systemd/systemd_%.bbappend
We got serveral systemd services error after merge systemd code, like:
[FAILED] Failed to mount Huge Pages File System.
[FAILED] Failed to mount POSIX Message Queue File System.
[FAILED] Failed to start Rebuild Hardware Database.
[FAILED] Failed to start Commit a transient machine-id on disk.
[FAILED] Failed to start Platform Persistent Storage Archival.
All these failed get similar situation
Active: failed (Result: start-limit-hit)
Condition: start condition failed at ...
=> 1. get start-limit-hit, 2. condition failed
These error cause by systemd change: ed8fbbf1745c6a
Bug: https://github.com/systemd/systemd/issues/21025
So, bump the systemd srcrev to 4fa9d8f1452
Gerrit …
=> meta-quanta: meta-olympus-nuvoton: fix systemd services error

meta-quanta/meta-olympus-nuvoton/conf/local.conf.sample
Due to we cannot build pass with package_ipk, use package_rpm first.
=> meta-quanta: meta-olympus-nuvoton: move PACKAGE_CLASSES to rpm

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/interfaces/bmcweb/0018-redfish-log_services-fix-createDump-functionality.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/interfaces/bmcweb_%.bbappend
Correct our previous patch for this functionality with the latest upstream
0018-redfish-log_services-fix-createDump-functionality.patch
=> meta-quanta: olympus-nuvoton: bmcweb: update patch

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/sensors/dbus-sensors/0001-Add-more-PSU-devices-support.patch
Update dbus sensor patch to fix build break for distro olympus-entity
=> meta-quanta:meta-olympus-nuvoton:dbus-sensors: update patch

meta-quanta/meta-olympus-nuvoton/recipes-support/nss-pam-ldapd/nss-pam-ldapd/nslcd.service, meta-quanta/meta-olympus-nuvoton/recipes-support/nss-pam-ldapd/nss-pam-ldapd_%.bbappend
When LDAP configuration change by bmcweb, the nslcd will be disabled
first, then be enabled after configuration modified. This action not
take much time, then systemd will count the restart. In LDAP testing,
the case will reach "start-limit-hit" after we continue update LDAP
configuration or update configuraion after BMC reboot.
Set StartLimitIntervalSec=0 to disable the restart counter, because
nslcd service may restart many time in real case.
Ref: man systemd.unit
Test:
redfish/account_service/test_ldap_configuration.robot
see https://github.com/openbmc/docs/blob/master/CONTRIBUTING.md#submitting-changes-via …
=> meta-quanta: meta-olympus-nuvoton: nslcd: disalbe rate limiting

poky/bitbake/lib/bb/fetch2/git.py
github is dropping support for git protocol in Git urls. Add code to remap
this to https in a way that could be used in older bitbake versions.
(Bitbake rev: f05e19135b3ddee509c0cb427b3b9376bb4738d1)
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
cherr-pick from poky gerrit commit: 5fb6b453f633796f28e230420e17b644adde8b11
=> bitbake: fetch/git: Handle github dropping git:// support

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/sel-logger/phosphor-sel-logger_%.bbappend
The x86 power control already report host power on/off log with
redifsh journal format, we don't need enable this function in
sel logger.
=> meta-quanta :olympus-nuvoton: sel-logger: remove log pulse

meta-nuvoton/recipes-kernel/linux/linux-nuvoton_git.bb
Jason M. Bills (1):
Fix truncated WrEndPointConfig MMIO command
Joseph Liu (2):
gpio: nuvoton spgio: fixed format
gpio: nuvoton: sgpio: fix incorrect index of array
Medad CChien (1):
driver: edac: npcm8xx: Support Cadence DDR4-ECC EDAC Driver
Stanley Chu (9):
i3c: master: svc: remove free_irq from remove function
i3c: Add description of setaasa variable in i3c_bus structure
i3c: Add I3CDEV support
npcm845-evb: enable I3C bus2 for connecting with SPD5118 module
arm: dts: npcm845-evb: add a PMIC i3c slave device on bus 2
misc: eeprom: Add remove function for spd5118 driver
i3c: i3cdev: update i3cdev driver
arm: dts: npcm845-evb: remove devices on i3c2
arm: dts: npcm845-evb: remove spi-rx-bus-width property from FIU1 node
Tim Lee (4):
dt-bindings: hwmon: Add NPCM7XX MCU I2C ADC support …
=> meta-nuvoton: linux-nuvoton: bump srcrev: 9ecbd27ae9..6dbbbd5bb7

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/sensors/pldmsensors_git.bb, meta-nuvoton/recipes-bsp/images/npcm7xx-bingo-native_git.bb, meta-nuvoton/recipes-bsp/images/npcm7xx-igps-native_02.01.12.bb, meta-nuvoton/recipes-nuvoton/ipmi/nuvoton-ipmi-oem_git.bb, meta-nuvoton/recipes-nuvoton/loadmcu/loadmcu.bb, meta-nuvoton/recipes-nuvoton/loadsvf/loadsvf_git.bb, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/sensors/pldmsensors_git.bb, meta-quanta/meta-olympus-nuvoton/recipes-x86/asd/asd.bb, meta-quanta/meta-olympus-nuvoton/recipes-x86/crashdump/crashdump_git.bb, meta-quanta/meta-olympus-nuvoton/recipes-x86/node-manager/phosphor-node-manager-proxy_git.bb
Github is no longer support git protocol from now, update all Nuvoton
own recipe to use https protocol instead.
=> meta-nuvoton/buv-runbmc/olympus-nuvoton: use https intead of git

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-core/systemd/systemd/0001-network-Fix-crash-while-dhcp4-address-gets-update.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-core/systemd/systemd/0001-networkd-create-new-socket.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-core/systemd/systemd_%.bbappend
Symptom:
systemd-networkd: Assertion 'a' failed at src/network/networkd-address.c:1868,
function address_is_ready(). Aborting.
Solution:
systemd-networkd: Fix crash while dhcp4 address gets update
https://github.com/systemd/systemd/pull/18306/commits/74b1c99521d7a97093ccfdf8ce68a12aff54f639
Verify:
Run Stress Test Arbel automation test.
=> meta-evb: evb-npcm845: systemd: fixed systemd network crash

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/configuration/entity-manager/NUVOTON-ARBEL-EVB.json, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/sensors/dbus-sensors/0002-Add-thermal-zone-support-in-hwmon-sensor.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/sensors/dbus-sensors_%.bbappend
Add thermal zone support as hwmon temperture sensor, and also
update entity manager configuration.
=> meta-evb-npcm845: dbus-sensors: add thermal zone support

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-evb-npcm845/packagegroups/packagegroup-evb-npcm845-apps.bb, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-flash_%.bbappend
Note: Use pci-mailbox1 to transfer image
reboot BMC after image is verifed
=> meta-evb: nuvoton: evb-npcm845: support IPMI inband firmware update

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/ipmi/phosphor-ipmi-host/0001-Correct-IPMI-firmware-revision-report.patch, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/ipmi/phosphor-ipmi-host/0001-Correct-IPMI-firmware-revision-report.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend
revision
Apply patch for correct IPMI firmware revision report
=> meta-olympus-nuvoton/meta-buv-runbmc: phosphor-ipmi-host: correct fw

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/smbios/smbios-mdr_%.bbappend
Symptom:
1. Too few "Memory" FRUs found, found only 0.
2. MemorySummary State is not 'Enabled'.: Enabled != Disabled.
3. **ERROR** The following variable is not within the expected range: num_cpus: 0 <int>
Journal log:
olympus-nuvoton smbiosmdrv2app[490]: Anchor String not found
olympus-nuvoton smbiosmdrv2app[490]: Unsupported SMBIOS table version
Root cause:
Intel add SMBIOS version check mechanism to verify the version whether match their BIOS sent table version.
However, out BIOS didn’t send it then cause smbiosmdrv2app report error cause related test items got failed.
Solution:
Parsing SMBIOS table without checking version.
Tested:
test_systems_inventory.robot "Verify CPU And Core Count"
test_systems_inventory.robot "Get Memory Inventory Via Redfish And Verify" …
=> meta-quanta: olympus-nuvoton: smbios: no SMBIOS version check

meta-nuvoton/recipes-bsp/u-boot/u-boot-common-nuvoton.inc
=> meta-nuvoton: move u-boot branch from npcm7xx-v2019.01 to npcm-v2021.04

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/interfaces/bmcweb/0005-bmcweb-chassis-add-indicatorLED-support.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/interfaces/bmcweb_%.bbappend
Symptom:
Resolving variable '${resp.dict["IndicatorLED"]}' failed: KeyError: 'IndicatorLED'
Root cause:
OpenBMC bmcweb didn’t support Chassis IndicatorLED redfish property
Solution:
Adding Chassis IndicatorLED support for compatible with current bmcweb design
Tested:
test_led_indicator_asserted.robot "Verify LED BMC Heartbeat Asserted At Standby"
test_led_indicator_asserted.robot "Verify LED BMC Heartbea Units Asserted At Runtime"
=> meta-quanta: olympus-nuvoton: bmcweb: add Chassis IndicatorLED support

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/flash/phosphor-software-manager/0001-Support-update-uboot-with-emmc-image.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/flash/phosphor-software-manager/support_update_uboot_with_emmc_image.patch
Update phosphor-software-manager patch for fix update emmc image error
from phosphor ipmi flash.
Also update patch for meta-buv-runbmc.
=> meta-olympus-nuvoton: update software manager patch

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/conf/machine/evb-npcm845.conf, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-evb-npcm845/packagegroups/packagegroup-evb-npcm845-apps.bb, meta-nuvoton/classes/image_types_phosphor_nuvoton_npcm8xx.bbclass, meta-nuvoton/recipes-bsp/arm-trusted-firmware/arm-trusted-firmware.inc, meta-nuvoton/recipes-nuvoton/images/nuvoton-mkimage.bb, meta-nuvoton/recipes-security/optee/optee-os.bb
Move optee and atf task dependency to mkimage recipe to avoid pacakge
manifest install error.
=> meta-nuvoton: fix tz branch build break

README.md, meta-nuvoton/recipes-bsp/u-boot/files/u-boot-env-emmc.txt
After we update U-Boot to 2021.04, we also move move default mmc to mmc
0 for making U-Boot and Kernel have same device settings. Update the
readme file and U-Boot environment file for this change.
=> Update Readme due to default mmc move to mmc 0

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/interfaces/bmcweb/0001-Handle-now-allow-execption-in-account-service.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/interfaces/bmcweb_%.bbappend, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/users/phosphor-user-manager/0001-Throw-NotAllowed-when-delete-or-disable-root.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/users/phosphor-user-manager_%.bbappend
Throw NotAllowed exeception instead of InternalFailure when delete root.
=> olympus-nuvoton: throw not allow when delete root

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/interfaces/bmcweb/0002-Create-new-user-without-SSH-group.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/interfaces/bmcweb_%.bbappend
Remove SSH from default groups when create new user.
Test:
redfish/account_service/test_user_account.robot
=> meta-olympus-nuvoton: create user without ssh group

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/configuration/buv-runbmc-yaml-config.bb, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/configuration/buv-runbmc-yaml-config/buv-runbmc-ipmi-inventory-sensors.yaml, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/sel-logger/phosphor-sel-logger_%.bbappend
Enable send-to-logger feature of phosphor-sel-logger.
Add buv-runbmc-ipmi-inventory-sensors.yaml file.
Modify the bb and bbappend file.
=> meta-buv-runbmc: enable send-to-logger feature of phosphor-sel-logger

meta-nuvoton/recipes-phosphor/ipmi/phosphor-ipmi-config.bbappend
Set Nuvoton machine default has empty entity map, user can overwrite
ENTITY_MAPPING and set up entity-map.json to replace it.
test:
ipmi/test_ipmi_sdr.robot
=> meta-nuvoton: set default empty entity map

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/conf/local.conf.sample
Miss a double quotation mark which caused following build error:
ERROR: ParseError at local.conf:6: unparsed line: 'USER_CLASSES ?= "buildstats'
=> [runbmc] Fix typo caused runbmc build error.

meta-nuvoton/recipes-kernel/linux/linux-nuvoton_git.bb
Brian Ma (1):
npcm7xx: defconfig: remove SYSFS_DEPRECATED
Jason Ling (1):
google: mtd: spi-nor: add hoth support
Tomer Maimon (1):
Merge pull request #102 from jclaz/NPCM-5.10-OpenBMC
Signed-off-by: Jason Ling <jasonling@google.com>
=> nuvoton-kernel: uprev 12abb777ddca..528f1f0c43c7

meta-nuvoton/recipes-bsp/u-boot/u-boot-common-nuvoton.inc
Jason Ling (1):
spi-nor-id: add support for Google-Hoth
Tested:
evb-npcm845 still builds fine
Signed-off-by: Jason Ling <jasonling@chromium.org>
=> nuvoton: u-boot: uprev 0b15c70221..0c5ae0f0fa

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/ipmi/phosphor-ipmi-host/0001-Add-set-BIOS-version-support.patch, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/ipmi/phosphor-ipmi-host/0001-Fix-firmware-version-missing-at-dev-tag.patch, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/ipmi/phosphor-ipmi-host/0001-Add-set-BIOS-version-support.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/ipmi/phosphor-ipmi-host/0001-Fix-firmware-version-missing-at-dev-tag.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend
When our device version contains dev like: 2.12.0-dev-1361..., the ipmi
mc info command cannot return firmware version correctly. Fix it by
modify convertVersion function.
Also update set BIOS version patch with newest version.
=> meta-olympus-nuvoton: fix ipmi mc info error

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/flash/phosphor-software-manager/0004-Add-support-for-MCU-firmware-upgrade.patch, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/flash/phosphor-software-manager_%.bbappend, meta-nuvoton/recipes-phosphor/webui/webui-vue/0002-Add-Nuvoton-MCU-firmware-support.patch, meta-nuvoton/recipes-phosphor/webui/webui-vue_%.bbappend
This feature could upgrade MCU FW via WebUI.
Test done:
No build error.
Boot normally.
Upgrade MCU FW via WebUI OK.
/xyz/openbmc_project/software/mcu_active DBus object work well.
=> Add support for MCU FW upgrade.

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/ipmi/phosphor-ipmi-config.bbappend, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend
Update phosphor-ipmi-host recipe to fix dynamic sensor not work in
entity manager distro.
And also fix build break if current commit at annotated tag
=> meta-buv-runbmc: fix ipmi sdr list error

meta-nuvoton/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend
=> meta-nuvoton: ipmi: remove patch that fixed ipmid crash in 64bit system

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/dbus/phosphor-dbus-interfaces/0001-Software-Add-CPLD-VersionPurpose.patch, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/dbus/phosphor-dbus-interfaces_%.bbappend, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/flash/phosphor-software-manager/0002-porting-bios-verify-feature.patch, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/flash/phosphor-software-manager/0005-Add-support-for-CPLD-firmware-upgrade.patch, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/flash/phosphor-software-manager_%.bbappend, meta-nuvoton/recipes-nuvoton/loadsvf/files/cpld-update.service, meta-nuvoton/recipes-nuvoton/loadsvf/files/cpld-update.sh, meta-nuvoton/recipes-nuvoton/loadsvf/loadsvf_git.bb, meta-nuvoton/recipes-phosphor/webui/webui-vue/0003-Add-Nuvoton-CPLD-firmware-support.patch, meta-nuvoton/recipes-phosphor/webui/webui-vue_%.bbappend
Add support for CPLD FW upgrade via WebUI.
Test done:
No build error.
Not boot error.
CPLD FW upgrade via WebUI function works fine.
CPLD FW version (file name) could be shown on WebUI.
=> Add support for CPLD FW upgrade via WebUI.

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0012-Force-self-test-OK.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0012-Force-self-test-OK.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend
The BMC functions must always ready, maybe we can implement the function
later.
=> meta-evb-npcm845: Force set self test command pass

meta-nuvoton/recipes-bsp/images/npcm7xx-bingo-native_git.bb
Bingo 0.0.5 is required for Arbel. It is also backward compatible for Poleg.
=> meta-nuvoton: npcm7xx-bingo: upgrade latest version 0.0.5 support Arbel

meta-nuvoton/recipes-bsp/u-boot/u-boot-common-nuvoton.inc
use new uboot-2021 commit to fix olympus reset failed.
=> meta-nuvoton: update uboot source

meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-net/0001-Revert-Remove-HMAC-SHA1-from-Authentication-Integrit.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-net_%.bbappend
Due to Wiwynn requirement, add back deprecated authentication algorithm
support.
Now we can execute ipmi command like below:
ipmitool -H <BMCIP> -I lanplus -U <username> -P <password> -C 3 mc info
=> meta-scm-npcm845: Allow HMAC-SHA1 authentication algorithm

meta-evb/meta-evb-nuvoton/meta-scm-npcm845/conf/machine/scm-npcm845.conf
By default Openbmc design, /var/log mount on tmpfs. Change the log path
to RW file system.
=> meta-scm-npcm845: mount /var/log persistent

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/network/phosphor-network_%.bbappend, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/network/phosphor-network_%.bbappend
Save MAC address to U-Boot environment to avoid missing MAC addrress
adfer update BMC image.
=> meta-evb-npcm845: save MAC address to U-boot env

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0014-Add-SEL-event-after-SEL-clear.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0014-Add-SEL-event-after-SEL-clear.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend
Follow MS. spec. 4.1.37, we need add a SEL after SEL clear command
executed.
=> meta-scm-npcm845: Add SEL after SEL clear command

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0009-implement-warm-reset-command.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0016-Add-reset-SEL.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0016-Add-reset-SEL.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend
For customer request, add SEL after execute ipmi reset command.
=> meta-scm-npcm845: add SEL after execute ipmi reset

meta-nuvoton/recipes-kernel/linux/linux-nuvoton_git.bb
Joseph Liu (1):
driver: gpio: npcm-sgpio: inactive sgpio before disabling irq
dts: Remove legacy VCD/ECE entries
Stanley Chu (1):
i3c: master: svc: drop debug log
Tomer Maimon (1):
udc: npcm: Fix UDC8 setting
=> meta-nuvoton: linux-nuvoton: srcrev bump 8a819af..e705947

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0018-Add-session-RemoteMACAddress-support.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-net/0001-Add-RemoteIPAddr-support.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-net_%.bbappend, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0018-Add-session-RemoteMACAddress-support.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-net/0001-Add-RemoteIPAddr-support.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-net_%.bbappend
Add support ipmi session command get remote MAC address feature, here we
simply search ARP table by read /proc/net/arp.
=> meta-scm-npcm845: Add ipmi session command get mac

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/state/phosphor-post-code-manager/0001-delay-serialize.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/state/phosphor-post-code-manager_%.bbappend, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/state/phosphor-post-code-manager/0001-delay-serialize.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/state/phosphor-post-code-manager_%.bbappend
We found during SCM boot, we will receive more than dozzen of POST code
in a second. That will cause POST code manager hang due to the service
perform serialize operation when get each POST code. Pening the
serialize work if get POST code to quick, and perform one more serialize
when we get boot complete event.
=> meta-scm-npcm845: fix post code hang issue

meta-nuvoton/classes/image_types_phosphor_nuvoton_npcm8xx.bbclass
Tested: Boot test passed with correct image version.
Arbel BootBlock Version 0.2.1
Arbel TIP FW L0 Version 0.3.6
Arbel TIP FW L1 Version 0.2.1
=> meta-nuvoton: classes: remove unused variables to improve readability

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-buv-runbmc/packagegroups/packagegroup-buv-runbmc-apps.bb
Test done:
No build error (DISTRO=buv-entity bitbake obmc-phosphor-image)
Boot OK.
systemctl status xyz.openbmc_project.EntityManager.service work OK.
ipmitool sdr
=> meta-evb: meta-evb-nuvoton: meta-buv-runbmc: fix buv-entity build error

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-evb-npcm845/boot-health/boot-health.bb, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-evb-npcm845/boot-health/files/scm-boot-health.service, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-evb-npcm845/packagegroups/packagegroup-evb-npcm845-apps.bb, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0016-Add-reset-SEL.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0021-sensor-reading-optional-zero.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0016-Add-reset-SEL.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0021-sensor-reading-optional-zero.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-scm-npcm845/boot-health/boot-health.bb, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-scm-npcm845/boot-health/files/scm-boot-health.service, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-scm-npcm845/packagegroups/packagegroup-scm-npcm845-apps.bb
Add BMC health SPI boot SEL to match OEM spec.
Move oem_health sensor number from 0xFF to 0xEF.
And let get senor reading always return optional byte for test criteria.
=> meta-scm-npcm845: Add BMC health SPI boot SEL

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend
Test Done:
DISTRO=olympus-entity bitbake obmc-phosphor-image
DISTRO=buv-entity bitbake obmc-phosphor-image
olympus boot OK.
ipmitool sdr test OK on olympus.
Signed-off-by: jhkang <jhkang@nuvoton.com>
=> fix DISTRO build error for buv and olympus

meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/leds/phosphor-led-manager/service-override.conf
Use mapper wait to wait required object path create.
=> meta-scm-npcm845: fix led-manager startup errors

meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/sensors/dbus-sensors/0008-increase-adc-max-reading.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/sensors/dbus-sensors_%.bbappend
To avoid the sensor reading and threshold error after IPMI scaling.
The current ADC max reading is const value 1.8 / [scale factor].
When we read the 1V8 power, we will set scale factor = 1, and this time
max reading will be 1.8. But in real world the power voltage may greater
than 1.8, may 1.85 or 1.9. In this case, we will recieve error reading
after IPMI scaling.
=> meta-scm-npcm845: increase adc sensor max reading

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0024-update-chassishandler-from-intel-oem-ipmi.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0025-save-no-supported-boot-options.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0025-save-no-supported-boot-options.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend
Save the boot options which Openbmc is not supported, and load the saved
data when execute IPMI command get system boot options.
=> meta-scm-npcm845: save IPMI system boot options

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/sensors/dbus-sensors/0001-intrusionsensor-Add-polling-event-status-by-sysfs.patch, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/sensors/dbus-sensors_%.bbappend
E.g. the json config as below.
{
"Class": "Sysfs",
"FilePath": "/sys/class/rtc/rtc0/intrusion_timestamp",
"Name": "Chassis Intrusion Sensor",
"Type": "ChassisIntrusionSensor"
}
=> intrusionsensor: Add polling event status by sysfs.

meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-kernel/linux/linux-nuvoton/0013-Add-pmbus-driver-for-MAX16550.patch
Update the kernel driver MAX16550 power parameter with real Rload.
=> meta-scm-npcm845: update MAX16550 power parameter

meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/flash/phosphor-software-manager/support_update_uboot_with_emmc_image.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/flash/phosphor-software-manager_%.bbappend
Update software manager update script to support update eMMC image to
flash U-Boot image on SPI flash.
=> meta-scm-npcm845: support eMMC image update U-Boot.

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/sensors/dbus-sensors/0001-intrusionsensor-Add-polling-event-status-by-sysfs.patch
meta-buv-runbmc: dbus-sensors: intrusionsensor: Add check and record intrusion timestamp mechanism.
=> meta-buv-runbmc: dbus-sensors: intrusionsensor: Add check and record intrusion timestamp mechanism.

meta-phosphor/recipes-phosphor/webui/webui-vue_git.bb
Update webui-vue recipe to avoid build depend package nlf-native.
=> webui-vue: bump srcrev: 12dc20c37...f763cd2e3

meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-kernel/linux/linux-nuvoton/0004-kernel-scm-dts.patch
Set GPIO155 default function to mmcrst.
=> meta-scm-npcm845: update DTS mmcrst_pins

meta-phosphor/recipes-phosphor/interfaces/bmcweb_git.bb
Update bmcweb version to fix update service fwUpdateErrorMatcher cannot
work issue.
=> bmcweb: bump srcrev f5e29f33e...e1cc4828

meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-kernel/linux/linux-nuvoton/0004-kernel-scm-dts.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-kernel/linux/linux-nuvoton/0016-WA-fix-watchdog-bootstatus-incorrect.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-kernel/linux/linux-nuvoton_%.bbappend, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0027-implement-chassis-acfail-status.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend
Use BMC status LastRebootCause is POR to set chassis AC fail status.
In normal reset case we use soft reset or watchdog reset, once we get
POR, it should be AC fail or first time boot.
=> meta-scm-npcm845: update chassis AC fail status

meta-nuvoton/recipes-bsp/images/npcm8xx-bootblock_0.2.2.bb
Update the correct license URL on Github.
=> meta-nuvoton: fix bootblock build warning

meta-nuvoton/recipes-kernel/linux/linux-nuvoton_git.bb
Marvin Lin (8):
dts: Reduce reserved video memory from 32M to 24M
driver: edac: Support error injection via debugfs
driver: edac: Remove sysfs error injection
dts: npcm845-evb: Move video memory to 0x33400000
driver: media: platform: Increase polling timeout to 300ms
driver: edac: Code refactoring
driver: media: Sync with upstream refinements
Revert "dts: npcm845-evb: Move video memory to 0x33400000"
Mia Lin (4):
RTC: nuvoton: Add nuvoton real time clock driver
dt-bindings: rtc: nuvoton: add NCT3018Y Real Time Clock
driver: rtc: add intrusion event detection
driver: rtc: Add record intrusion and vcc drop timestamps when bmc boots up.
Stanley Chu (1):
i3c: master: svc: adjust clock duty cycle
Tomer Maimon (4):
arm64: nuvoton: remove unused timer GIC_SPI IRQs
spi: npcm-fiu: handle SPI-X …
=> meta-nuvoton: linux-nuvoton: srcrev bump e705947..d37182b

meta-nuvoton/recipes-kernel/linux/linux-nuvoton_git.bb
driver: edac: Sync with upstream changes
Allen Kang (1):
arm: dts: Modify runbmc-olympus dts and pincfg.dtsi for kernel 5.15 grading
Joel Stanley (1):
net: npcm: Remove superfluous logging
Tomer Maimon (1):
net: emc: version 3.9.4
Jim Liu (3):
driver: gpio: nuvoton: add sgpio driver
drivers: gpio: add NPCM8xx SGPIO dts node
arm64: dts: nuvoton: fix build error for video dts node
Signed-off-by: Allen Kang <jhkang@nuvoton.com>
=> meta-nuvoton: linux-nuvoton: srcrev bump cc7e2206...0ba165da

meta-evb/meta-evb-nuvoton/meta-scm-npcm845/conf/machine/scm-npcm845.conf, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-kernel/linux/linux-nuvoton/0001-dts-scm-flash-partition-mtd0-only.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-kernel/linux/linux-nuvoton/0004-kernel-scm-dts.patch
Update partition layout and DTS to extend U-Boot size.
Signed-off-by: Brian Ma <chma0@nuvoton.com>
=> meta-scm-npcm845: extend U-Boot size to 4MB

meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-kernel/linux/linux-nuvoton/dts-supports-legacy-vcd-ece-drivers.patch, meta-quanta/meta-olympus-nuvoton/recipes-kernel/linux/linux-nuvoton/dts-supports-legacy-vcd-ece-drivers.patch
Update legacy VCD/ECE DTS patch for kernel 5.15.
=> legacy-kvm: Update legacy VCD/ECE DTS patch for kernel 5.15

meta-quanta/meta-olympus-nuvoton/recipes-kernel/linux/linux-nuvoton/0001-dts-fix-firmware-update.patch, meta-quanta/meta-olympus-nuvoton/recipes-kernel/linux/linux-nuvoton_%.bbappend
Fix image-u-boot too big and flash permission denied issues
Signed-off-by: yhyang2 <yhyang2@nuvoton.com>
=> meta-quanta: meta-olympus-nuvoton: fix firmware update issues

meta-nuvoton/recipes-kernel/linux/linux-nuvoton/npcm8xx_defconfig
EDAC config name was unexpectedly changed in commit 494e423. Just correct it back.
=> meta-nuvoton: Correct EDAC config name

meta-nuvoton/recipes-kernel/linux/linux-nuvoton_git.bb
Jim Liu (1):
dts: arm: nuvoton: npcm7xx: add buv dts files
net: stmmac: Add NCSI support for NPCM845 EVB
=> meta-nuvoton: linux-nuvoton: bump srcrev 60b96c3b...73b99eec

meta-quanta/meta-olympus-nuvoton/conf/machine/olympus-nuvoton.conf
Note:
The flash size setting is modified to 64MB, it will boot failed without this patch.
Signed-off-by: Allen Kang <jhkang@nuvoton.com>
=> meta-quanta: meta-olympus-nuvoton: fix flash boot failed

meta-nuvoton/recipes-phosphor/interfaces/bmcweb/0001-Fix-WS-connection-failed.patch, meta-nuvoton/recipes-phosphor/interfaces/bmcweb_%.bbappend
Add patch to fix web socket connection failed.
Issue link: https://github.com/openbmc/bmcweb/issues/243
=> meta-nuvoton: bmcweb: Add patch to fix web socket connection failed

meta-quanta/meta-olympus-nuvoton/recipes-core/systemd/systemd_%.bbappend
Fix Olympus build error because of OpenBmc updating.
Test done:
- Build OK
Signed-off-by: Allen Kang <jhkang@nuvoton.com>
=> meta-quanta: meta-olympus-nuvoton: systemd: fix olympus build error

meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/console/obmc-console/server.ttyS1.conf
We should keep only one obmc-console server service without socket id for default SOL(web, ipmi) use. Others should set socket id to avoid conflict.
Solved: host SOL un-expected behavior.
Signed-off-by: Brian Ma <chma0@nuvoton.com>
=> meta-scm-npcm845: add socket id for ttyS1 console
