meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/ipmi/phosphor-ipmi-host.bbappend, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/ipmi/phosphor-ipmi-host/0001-rmq.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/ipmi/phosphor-ipmi-host/xyz.openbmc_project.Control.Host.conf
add SendMessge and GetMessage command handler to forward IPMB messgaes to IPMB channel
=> host-ipmid: support RMQ

meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/interfaces/phosphor-rest/0002-add-vm-handler.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/webui/phosphor-webui/0002-Implement-VM-in-webui.patch
1. Use http request to enable/disable MSTG
=> meta-evb-npcm750: Update Patch files for VM

meta-evb/meta-evb-nuvoton/meta-evb-npcm750/README.md, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/dlc/ldap-support-user-management/recipes-devtools/python/pamela/pamela-user-manage-extra-support.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/dlc/ldap-support-user-management/recipes-devtools/python/pamela_%.bbappend, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/dlc/ldap-support-user-management/recipes-phosphor/base-files/base-files_%.bbappend, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/dlc/ldap-support-user-management/recipes-phosphor/base-files/files/nsswitch.conf, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/dlc/ldap-support-user-management/recipes-phosphor/dropbear/dropbear/dropbear-pam-sesssion-support.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/dlc/ldap-support-user-management/recipes-phosphor/dropbear/dropbear_%.bbappend, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/dlc/ldap-support-user-management/recipes-phosphor/images/obmc-phosphor-image.bbappend, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/dlc/ldap-support-user-management/recipes-phosphor/interfaces/phosphor-rest/0001-meta-evb-npcm750-Add-support-for-LDAP-login.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/dlc/ldap-support-user-management/recipes-phosphor/interfaces/phosphor-rest/0001-meta-evb-npcm750-Add-user-password-update-support-fo.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/dlc/ldap-support-user-management/recipes-phosphor/interfaces/phosphor-rest_%.bbappend, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/dlc/ldap-support-user-management/recipes-phosphor/nss-pam-ldapd/files/nslcd.conf, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/dlc/ldap-support-user-management/recipes-phosphor/nss-pam-ldapd/files/user-manage-ldap.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/dlc/ldap-support-user-management/recipes-phosphor/nss-pam-ldapd/nss-pam-ldapd%.bbappend, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/dlc/ldap-support-user-management/recipes-phosphor/openldap/files/ldap.conf, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/dlc/ldap-support-user-management/recipes-phosphor/openldap/openldap_%.bbappend, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/dlc/ldap-support-user-management/recipes-phosphor/pam/libpam/files/common-account, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/dlc/ldap-support-user-management/recipes-phosphor/pam/libpam/files/common-auth, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/dlc/ldap-support-user-management/recipes-phosphor/pam/libpam/files/common-password, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/dlc/ldap-support-user-management/recipes-phosphor/pam/libpam/files/common-session, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/dlc/ldap-support-user-management/recipes-phosphor/pam/libpam_%.bbappend, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/dlc/ldap-support-user-management/recipes-phosphor/webui/phosphor-webui/0001-Add-user-password-update-support-for-LDAP.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/dlc/ldap-support-user-management/recipes-phosphor/webui/phosphor-webui_%.bbappend
1. The dlc of user management is also provided.
=> meta-evb-npcm750: Add LDAP server setup and test in README.md

meta-evb/meta-evb-nuvoton/meta-evb-npcm750/README.md
=> meta-evb-npcm750: README: update JTAG Master

meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/ipmi/phosphor-ipmi-host/0003-add-clear-atn.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend
clear attention when message queue is empty
@stanleychuys
=> meta-evb-npcm750: ipmid add clear atn

meta-phosphor/nuvoton-layer/recipes-phosphor/ipmi/phosphor-ipmi-flash/bios-update.sh, meta-phosphor/nuvoton-layer/recipes-phosphor/ipmi/phosphor-ipmi-flash/bios-verify.sh, meta-phosphor/nuvoton-layer/recipes-phosphor/ipmi/phosphor-ipmi-flash/phosphor-ipmi-flash-bios-update.service, meta-phosphor/nuvoton-layer/recipes-phosphor/ipmi/phosphor-ipmi-flash/phosphor-ipmi-flash-bios-verify.service, meta-phosphor/nuvoton-layer/recipes-phosphor/ipmi/phosphor-ipmi-flash/phosphor-ipmi-flash-bmc-verify.service, meta-phosphor/nuvoton-layer/recipes-phosphor/ipmi/phosphor-ipmi-flash_%.bbappend
=> meta-phosphor: nuvoton-layer: support BIOS update

meta-phosphor/nuvoton-layer/dlc/ldap-support-user-management/recipes-core/dropbear/dropbear/dropbear-pam-sesssion-support.patch, meta-phosphor/nuvoton-layer/dlc/ldap-support-user-management/recipes-core/dropbear/dropbear_%.bbappend, meta-phosphor/nuvoton-layer/dlc/ldap-support-user-management/recipes-extended/pam/libpam/files/common-password, meta-phosphor/nuvoton-layer/dlc/ldap-support-user-management/recipes-extended/pam/libpam/files/common-session, meta-phosphor/nuvoton-layer/dlc/ldap-support-user-management/recipes-extended/pam/libpam_%.bbappend, meta-phosphor/nuvoton-layer/dlc/ldap-support-user-management/recipes-phosphor/interfaces/bmcweb/0001-meta-evb-npcm750-add-bmcweb-login-from-ldap-with-Nuv.patch, meta-phosphor/nuvoton-layer/dlc/ldap-support-user-management/recipes-phosphor/interfaces/bmcweb_%.bbappend, meta-phosphor/nuvoton-layer/dlc/ldap-support-user-management/recipes-phosphor/ipmi/phosphor-ipmi-net/0001-support-ipmi-session-login-via-ldap.patch, meta-phosphor/nuvoton-layer/dlc/ldap-support-user-management/recipes-phosphor/ipmi/phosphor-ipmi-net_%.bbappend, meta-phosphor/nuvoton-layer/dlc/ldap-support-user-management/recipes-runbmc-nuvoton/packagegroups/packagegroup-runbmc-nuvoton-apps.bb, meta-phosphor/nuvoton-layer/dlc/ldap-support-user-management/recipes-support/nss-pam-ldapd/files/ipmi-login-via-ldap-support.patch, meta-phosphor/nuvoton-layer/dlc/ldap-support-user-management/recipes-support/nss-pam-ldapd/files/nslcd.conf, meta-phosphor/nuvoton-layer/dlc/ldap-support-user-management/recipes-support/nss-pam-ldapd/files/user-manage-ldap.patch, meta-phosphor/nuvoton-layer/dlc/ldap-support-user-management/recipes-support/nss-pam-ldapd/nss-pam-ldapd%.bbappend, meta-phosphor/nuvoton-layer/dlc/ldap-support-user-management/recipes-support/openldap/files/ldap.conf, meta-phosphor/nuvoton-layer/dlc/ldap-support-user-management/recipes-support/openldap/openldap_%.bbappend
=> meta-evb-npcm750: Add LDAP support for user management

meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-kernel/linux/linux-nuvoton/0002-npcm-FIU-evb-3-4-addr.patch
=> add kernel patch for Winbond SPI

meta-phosphor/nuvoton-layer/dlc/ldap-support-user-management/recipes-core/dropbear/dropbear/dropbear-pam-sesssion-support.patch, meta-phosphor/nuvoton-layer/dlc/ldap-support-user-management/recipes-phosphor/interfaces/bmcweb/0001-meta-evb-npcm750-add-bmcweb-login-from-ldap-with-Nuv.patch
1. Update patches for dropbear and bmcweb packages
=> meta-phosphor: nuvoton-layer: update LDAP support for user management

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/webui/phosphor-webui/disable_show_delete_while_activating.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/webui/phosphor-webui_%.bbappend
Disable show delete button while firmware status is activating
=> meta-quanta: olympus-nuvoton: webui:

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/flash/phosphor-software-manager/force-reboot.service, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/flash/phosphor-software-manager_%.bbappend
Brian Ma
Implement show BIOS update progress
=> meta-quanta: meta-olympus-nuvoton: phosphor-software-manager srcrev bump 57566c3111...f6132c82d8

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/interfaces/bmcweb/Return-http-status-OK-after-ClearLog.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/interfaces/bmcweb_%.bbappend
=> meta-quanta: olympus-nuvoton: bmcweb: return http status OK instead of no content after ClearLog

meta-phosphor/nuvoton-layer/dlc/ldap-support-user-management/recipes-phosphor/interfaces/bmcweb/0001-meta-evb-npcm750-add-bmcweb-login-from-ldap-with-Nuv.patch
=> meta-quanta: olympus-nuvoton: bmcweb: update the LDAP patch

meta-evb/meta-evb-nuvoton/meta-evb-npcm750/README.md
=> meta-evb-npcm750: Update BMC firmware update via web description

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/dbus/phosphor-dbus-interfaces/boot_error.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/dbus/phosphor-dbus-interfaces_%.bbappend
=> meta-quanta: olympus-nuvoton: dbus-insterface: add Control/Boot error

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/logging/olympus-nuvoton-boot-error-native.bb, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/logging/olympus-nuvoton-boot-error/Boot.errors.yaml, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/logging/phosphor-logging-error-logs-native.bbappend
=> meta-quanta: olympus-nuvoton: add native error yaml for phosphor-logging

meta-quanta/meta-olympus-nuvoton/README.md
Add readme file about Olympus Nuvoton
=> meta-quanta: olympus-nuvoton: update README

README.md
=> Update RunBMC readme for target Olympus Nuvoton

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/flash/phosphor-software-manager_%.bbappend
srcrev bump cd0c833e12...923cec9ef5
Brian Ma
Support image-bmc for BMC firmware update
=> meta-quanta: meta-olympus-nuvoton: phosphor-software-manager

meta-phosphor/nuvoton-layer/dlc/ldap-support-user-management/recipes-phosphor/users/phosphor-user-manager_%.bbappend
=> meta-phosphor: nuvoton-layer: correct phosphor-user-manager bbappend

meta-quanta/meta-olympus-nuvoton/recipes-core/systemd/files/0001-networkd-create-new-socket.patch, meta-quanta/meta-olympus-nuvoton/recipes-core/systemd/systemd_%.bbappend
1. networkd: create new socket every time
=> meta-quanta:meta-olympus-nuvoton:recipes-core: systemd

meta-phosphor/nuvoton-layer/recipes-phosphor/ipmi/phosphor-ipmi-flash/bios-update.sh
disable ME function while update bios
=> meta-phosphor: nuvoton-layer: recipes-phosphor: phosphor-ipmi-flash:

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/ipmi/phosphor-ipmi-net/0001-Add-dbus-interface-for-sol-commands.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/ipmi/phosphor-ipmi-net/0002-Remove-Get-SOL-Config-Command-from-Netipmid.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/ipmi/phosphor-ipmi-net_%.bbappend, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/settings/phosphor-settings-manager/sol-default.override.yml, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/settings/phosphor-settings-manager_%.bbappend
1. Apply and modify Intel's patches for the ipmi_sol automation test.
2. phosphor-host-ipmid's commit id 7ec2c8f860419ae7e31733c3bab41526a3350e8a is also required.
=> meta-quanta: olympus-nuvoton: pass ipmi_sol automation test

meta-quanta/meta-olympus-nuvoton/README.md
Add a section about LDAP user authentication and privilege mapping in OpenBMC
=> meta-quanta: olympus-nuvoton: update README about LDAP

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/conf/layer.conf
=> meta-evb: meta-buv-runbmc: fix build break

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/ipmi/phosphor-ipmi-kcs_%.bbappend
1. Upload phosphor-ipmi-kcs_%.bbappend
=> meta-quanta: olympus-nuvoton: ipmi: add kcs device

meta-quanta/meta-olympus-nuvoton/recipes-olympus-nuvoton/packagegroups/packagegroup-olympus-nuvoton-apps.bb, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/datetime/bmc-time-sync.bb, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/datetime/bmc-time-sync/bmc-time-sync.service, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/datetime/bmc-time-sync/get_host_date.sh
remove pch time sync and using a shell script service instead
=> meta-quanta: olympus-nuvoton: use shell script replace pch-time-sync

meta-quanta/meta-olympus-nuvoton/recipes-olympus-nuvoton/packagegroups/packagegroup-olympus-nuvoton-apps.bb, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/smbios/smbios-mdrv2.bb
=> meta-quanta: olympus-nuvoton: smbios: add smbios-mdrv2 package

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/datetime/phosphor-time-manager/0001-Modify-dbus-call-style-for-calling-setTime.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/datetime/phosphor-time-manager_%.bbappend
1. Fix Verify Expired Server Certificate Replace test failure in obmc autotest test_certificate.robot.
=> meta-quanta: olympus-nuvoton: phosphor-time-manager

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/sensors/dbus-sensors/0001-add-Unit-property-in-Value-interface.patch, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/sensors/dbus-sensors/0002-add-Scale-d-bus-interface-property.patch, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/sensors/dbus-sensors/0003-Avoid-power-state-always-ADC-cannot-trigger-alarm.patch, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/sensors/dbus-sensors/0004-wait-mapper-for-avoid-failed-to-find-log.patch
=> meta-evb: buv-runbmc: dbus-sensors: fix patch failed error

meta-quanta/meta-olympus-nuvoton/README.md
=> meta-quanta: olympus-nuvoton: update readme for SMBIOS part

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/sel-logger/phosphor-sel-logger/0001-add-event-log-support.patch
=> meta-evb: buv-runbmc: phosphor-sel-logger: fix patch failed error

meta-quanta/meta-olympus-nuvoton/README.md
=> Add Virtual Media Performance

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/conf/distro/buv-entity.conf, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/conf/machine/buv-runbmc.conf
=> meta-buv-runbmc: add ext2 feature for support EXT2 tools

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-kernel/linux/linux-nuvoton/0006-driver-SPI-add-w25q01jv-support.patch, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-kernel/linux/linux-nuvoton_%.bbappend
=> meta-buv-runbmc: linux add SPI Nor flash w25q01jv support

meta-quanta/meta-olympus-nuvoton/recipes-olympus-nuvoton/loadmcu/files/mcu-update.service, meta-quanta/meta-olympus-nuvoton/recipes-olympus-nuvoton/loadmcu/files/mcu-version.sh, meta-quanta/meta-olympus-nuvoton/recipes-olympus-nuvoton/loadmcu/loadmcu.bb
=> meta-quanta: olympus-nuvoton: loadmcu: add support MCU firmware version

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/flash/phosphor-software-manager_%.bbappend
Tim Lee(1):
item_updater: item_updater: add support mcu firmware version verification
=> meta-quanta: olympus-nuvoton: software-manager: fixed srcrev 4c50791c

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/flash/phosphor-software-manager/mcu-release, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/flash/phosphor-software-manager_%.bbappend
=> meta-quanta: olympus-nuvoton: software-manager: add mcu-release file

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/interfaces/bmcweb/0010-bmcweb-fix-segmentation-fault-in-update-service.patch, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/interfaces/bmcweb_%.bbappend, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend
bump phosphor-host-ipmid srcrev 0dd10bb5e4..18ef684602
change bmcweb config from OECMAKE to OEMESON
=> meta-evb: buv-runbmc: fix build break

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/sensors/pldmsensors/pldmsensors.json, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/sensors/pldmsensors_git.bb, meta-quanta/meta-olympus-nuvoton/recipes-x86/pmci/libpldm-intel_%.bbappend
Note: update recipes-phosphor/sensors/pldmsensors/pldmsensors.json
recipes-phosphor/sensors/pldmsensors_git.bb
recipes-x86/pmci/libpldm-intel_%.bbappend
=> meta-quanta: meta-olympus-nuvoton: support pldm hysteresis function

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/flash/phosphor-software-manager/mcu-release, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/flash/phosphor-software-manager_%.bbappend
=> meta-quanta: olympus-nuvoton: software-manager: remove mcu-release file

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/sensors/pldmsensors_git.bb
Note: Stop resending PLDM request until PLDM device is on line
=> Update pldmsensors commit to support polling PLDM device

meta-quanta/meta-olympus-nuvoton/README.md, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/sensors/pldmsensors_git.bb
=> Update README.md for PLDMsensors

meta-quanta/meta-olympus-nuvoton/README.md
Update the link for PLDM to “PLDM sensor”.
=> Update README.md for PLDM sensors link

meta-quanta/meta-olympus-nuvoton/README.md
=> meta-quanta: olympus-nuvoton: update README for MCU Firmware Update

meta-nuvoton/recipes-kernel/linux/linux-nuvoton/0018-dts-runbmc-olympus-add-power-reset-button-and-post-c.patch, meta-nuvoton/recipes-kernel/linux/linux-nuvoton_git.bb, meta-quanta/meta-olympus-nuvoton/conf/machine/olympus-nuvoton.conf, meta-quanta/meta-olympus-nuvoton/recipes-olympus-nuvoton/packagegroups/packagegroup-olympus-nuvoton-apps.bb, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/dbus/phosphor-dbus-interfaces/0024-Add-the-pre-timeout-interrupt-defined-in-IPMI-spec.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/dbus/phosphor-dbus-interfaces/0025-Add-PreInterruptFlag-properity-in-DBUS.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/dbus/phosphor-dbus-interfaces_%.bbappend, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/watchdog/phosphor-watchdog/0001-Customize-phosphor-watchdog-for-Intel-platforms.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/watchdog/phosphor-watchdog/phosphor-watchdog.service, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/watchdog/phosphor-watchdog_%.bbappend, meta-quanta/meta-olympus-nuvoton/recipes-x86/chassis/x86-power-control/power-config-host0.json, meta-quanta/meta-olympus-nuvoton/recipes-x86/chassis/x86-power-control_%.bbappend
Signed-off-by: Joseph Liu <kwliu@nuvoton.com>
=> meta-quanta: olympus-nuvoton: chassis: support x86-power-control

meta-openembedded/meta-oe/recipes-extended/rsyslog/rsyslog/rsyslog.service, meta-openembedded/meta-oe/recipes-extended/rsyslog/rsyslog_8.2102.0.bb
=> meta-openembedded: rsyslog: update version 8.2006 to 8.2102

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/interfaces/bmcweb_%.bbappend
=> meta-quanta: olympus-nuvoton: bmcweb: remove dbus rest patch

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/conf/bblayers.conf.sample, meta-quanta/meta-olympus-nuvoton/conf/bblayers.conf.sample
make nuvoton layer at the bottom
=> meta-olympus-nuvoton: move layer sequence

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/configuration/entity-manager/F0B_BMC_MB.json
Add hotswap and export board information
=> meta-quanta: olympus-nuvoton: entity-manager: update configuration

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/classes/entity-utils.bbclass, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/conf/bblayers.conf.sample, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/conf/conf-notes.txt, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/conf/distro/arbel-evb-entity.conf, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-evb-npcm845/packagegroups/packagegroup-evb-npcm845-apps.bb, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/configuration/entity-manager/ARBEL_EVB_BMC.json, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/configuration/entity-manager_%.bbappend, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-fru_%.bbappend
1. add entity-utils.bbclass
2. add layer meta-intel-openbmc support
3. add distro arbel-evb-entity
4. add configuration ARBEL_EVB_BMC.json
5. update recipes phosphor-ipmi-fru to fix distro entity manager
=> Porting Arbel EVB entity manager distro

meta-quanta/meta-olympus-nuvoton/IPMI.md
update the ipmi message route in openbmc
=> meta-quanta: olympus-nuvoton: README update ipmi route

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/QUICK_SETUP.md, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/README.md
=> meta-evb: nuvoton: buv-runbmc: add QUICK_SETUP.md

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/README.md
=> meta-evb: nuvoton: evb-npcm845: readme: add i2c/espi description

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/flash/phosphor-software-manager_%.bbappend, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/inventory/olympus-nuvoton-inventory-cleanup/inventory-cleanup.yaml, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/network/phosphor-network_%.bbappend, meta-quanta/meta-olympus-nuvoton/recipes-x86/chassis/x86-power-control/power-config-host0.json
Fix following service have exited unsuccessfully issue.
xyz.openbmc_project.Inventory.Manager.service
xyz.openbmc_project.Chassis.Control.Power@0.service
=> meta-quanta: meta-olympus-nuvoton: fix services down after merge code

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/interfaces/bmcweb_%.bbappend
Eanble Dbus rest API for test cases
=> meta-quanta: meta-olympus-nuvoton: bmcweb: enable dbus rest API

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/README.md
=> Update README.md for ikvm and virtual media

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/README.md
=> Update README.md for EMMC

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-evb-npcm845/packagegroups/packagegroup-evb-npcm845-apps.bb, meta-phosphor/recipes-phosphor/ecc/phosphor-ecc_git.bb
=> meta-evb-npcm845: Support phosphor-ecc

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/README.md
=> meta-evb-npcm845: update README for FAN/PWM

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-kernel/linux/linux-nuvoton/0001-i2c-npcm-add-retry-probe-to-fix-sometime-SCL-SDA-low.patch, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-kernel/linux/linux-nuvoton_%.bbappend
meta-evb: add i2c retry probe feature to fixed SCL/SDA still low
=> meta-evb: removed degug patch and fixed build error

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/README.md
=> meta-evb: nuvoton: evb-npcm845 update README for BIOS POST Code

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/README.md
1. SMB
2. USB host/device
3. EMMC
4. AES/SHA/RNG/OTP
=> meta-evb: nuvoton: evb-npcm845 update README for uboot test

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/README.md
=> Update README.md for forcing ecc in linux

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/README.md
=> meta-evb: nuvoton: evb-npcm845: update README for SPIX

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ecc/phosphor-ecc/phosphor-ecc.service
Note: update edac path to
/sys/devices/system/edac/mc/mc0
=> meta-evb-npcm845: phosphor-ecc: update service file

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/README.md
=> meta-evb: nuvoton: npcm845: README: add FAN RPM convert formula

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/README.md
=> Update README.md for GPIO

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/README.md
=> meta-evb: nuvoton: evb-npcm845: README: PECI update

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/README.md
add description for how to enable forcing an ECC event
=> Update README.md for enabling forcing ECC event

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/README.md
=> meta-evb-npcm845: update README for GPIO

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/README.md
=> Update README.md for SIOX Stress Test

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/README.md
=> meta-evb: nuvoton: evb-npcm845: README: 64MB OpenBMC update

README.md
since we update use the eMMC image as default, add readme to descript it.
Preview:
https://github.com/minimada/openbmc/blob/readme1230/README.md
depend PR #332
=> update readme emmc image part

meta-quanta/meta-olympus-nuvoton/recipes-x86/chassis/x86-power-control/0003-workaround-for-fixing-unexpected-post-complete-deass.patch, meta-quanta/meta-olympus-nuvoton/recipes-x86/chassis/x86-power-control_%.bbappend
workaround for fixing unexpected post complete deassert event
=> meta-quanta: olympus-nuvoton: x86-power-control: add patch

meta-quanta/meta-olympus-nuvoton/recipes-x86/chassis/x86-power-control/0003-workaround-for-fixing-unexpected-post-complete-deass.patch
change to use lg2 function to print log according latest openbmc design
=> meta-quanta: olympus-nuvoton: x86-power-control: correct patch

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-x86/pmci/libmctp-intel_%.bbappend, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-x86/pmci/libpldm-intel_%.bbappend, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-x86/pmci/mctpd.bbappend, meta-nuvoton/recipes-bsp/u-boot/u-boot-common-nuvoton.inc, meta-nuvoton/recipes-kernel/linux/linux-nuvoton.inc, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/debug/olympus-nuvoton-debug-collector.inc, meta-quanta/meta-olympus-nuvoton/recipes-x86/pmci/libmctp-intel_%.bbappend, meta-quanta/meta-olympus-nuvoton/recipes-x86/pmci/libpldm-intel_%.bbappend, meta-quanta/meta-olympus-nuvoton/recipes-x86/pmci/mctpd.bbappend
Update none-bb files like inc or bbappend which use protocol git or ssh.
=> meta-nuvoton/buv-runbmc/olympus-nuvoton: use https intead of git

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-evb-npcm845/packagegroups/packagegroup-evb-npcm845-apps.bb, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-flash_%.bbappend
Note: Use pci-mailbox1 to transfer image
reboot BMC after image is verifed
=> meta-evb: nuvoton: evb-npcm845: support IPMI inband firmware update

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/logging/phosphor-logging/0001-Fix-wrong-type-of-TRANSACTION_ID-metadata.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/logging/phosphor-logging_%.bbappend
=> meta-evb-npcm845: phosphor-logging: fix wrong type of TRANSACTION_ID

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/conf/conf-notes.txt, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/conf/distro/arbel-evb-emmc-entity.conf, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/conf/distro/arbel-evb-entity.conf
Signed-off-by: Joseph Liu <kwliu@nuvoton.com>
Change-Id: I25c4dc78ead1ac13d23cc34609df154c9de44d25
=> meta-evb: nuvoton: evb-npcm845: add emmc entity manager distro

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend
Signed-off-by: Stanley Chu <yschu@nuvoton.com>
=> meta-evb-npcm845: ipmi: disable i2c whitelist check

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/conf/distro/arbel-evb-emmc-entity.conf, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/conf/distro/arbel-evb-entity.conf, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend
Remove phosphor ipmi fru for entity distro
=> meta-evb: meta-evb-nuvoton: meta-evb-npcm845: remove ipmi fru

meta-nuvoton/recipes-bsp/u-boot/u-boot-common-nuvoton.inc
Signed-off-by: Stanley Chu <yschu@nuvoton.com>
=> meta-nuvoton: u-boot-npcm8xx: bump srcrev be078ee1...5adc64c7

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/README.md
1.remove 64MB image description, because we already use 64MB image size
2.update hyperlinks
Change-Id: If2da26da594d3833d684e1c44cd2053114d03a30
=> meta-evb: nuvoton: evb-npcm845: update README

meta-nuvoton/recipes-graphics/obmc-ikvm/obmc-ikvm_%.bbappend
=> meta-nuvoton: obmc-ikvm: fix build break

meta-nuvoton/recipes-bsp/u-boot/u-boot-common-nuvoton.inc
old commit id have no olympus dts
=> meta-nuvoton: fix build fail

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/README.md
Add description for emulating NPCM7XX and NPCM8XX machines on QEMU.
=> meta-evb: nuvoton: evb-npcm845: readme: add QEMU

meta-quanta/meta-olympus-nuvoton/recipes-olympus-nuvoton/packagegroups/packagegroup-olympus-nuvoton-apps.bb
Add basic test program iperf3 and openssl engine
Signed-off-by: Brian Ma <chma0@nuvoton.com>
=> meta-olympus-nuvoton: add test binary

meta-nuvoton/recipes-connectivity/openssl/openssl_%.bbappend, meta-nuvoton/recipes-phosphor/ipmi/phosphor-ipmi-host/0001-Use-numeric-limit-is-intergral-replace-std-is-intergral.patch, meta-nuvoton/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend
Upload patched to fix build break.
=> Fix branch npcm master build break

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/configuration/entity-manager/NUVOTON-ARBEL-EVB.json
Update entity manager configuration CPU temperature part for update
dbus sensor code.
=> meta-evb-npcm845: update entity configuration

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-evb-npcm845/ipmi-bios-update/files/bios-update.sh, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-evb-npcm845/ipmi-bios-update/files/bios-verify.sh, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-evb-npcm845/ipmi-bios-update/files/config-bios.json, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-evb-npcm845/ipmi-bios-update/files/phosphor-ipmi-flash-bios-update.service, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-evb-npcm845/ipmi-bios-update/files/phosphor-ipmi-flash-bios-verify.service, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-evb-npcm845/ipmi-bios-update/ipmi-bios-update.bb, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-evb-npcm845/ipmi-bmc-update/ipmi-bmc-update.bb, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-evb-npcm845/ipmi-bmc-update/ipmi-bmc-update/bmc-verify.sh, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-evb-npcm845/ipmi-bmc-update/ipmi-bmc-update/config-bmc.json, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-evb-npcm845/ipmi-bmc-update/ipmi-bmc-update/df-mmc/bmc-verify.sh, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-evb-npcm845/ipmi-bmc-update/ipmi-bmc-update/df-mmc/config-bmc.json, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-evb-npcm845/ipmi-bmc-update/ipmi-bmc-update/df-mmc/phosphor-ipmi-flash-bmc-update.service, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-evb-npcm845/ipmi-bmc-update/ipmi-bmc-update/phosphor-ipmi-flash-bmc-verify.service, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-evb-npcm845/packagegroups/packagegroup-evb-npcm845-apps.bb, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-kernel/linux/linux-nuvoton/0001-dts-rename-spi3-system1-to-bios.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-kernel/linux/linux-nuvoton_%.bbappend, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/flash/phosphor-software-manager/obmc-flash-host-bios@.service, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/flash/phosphor-software-manager/restore_verify_bios.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/flash/phosphor-software-manager_%.bbappend, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0001-Add-Set-BIOS-version-support.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend
=> meta-evb: meta-evb-npcm845: Support BIOS update on spi3

meta-evb/meta-evb-nuvoton/meta-evb-npcm750/README.md
=> meta-evb-npcm750: Update README for evb-npcm750

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/network/phosphor-network/0001-Run-after-xyz-openbmc_project-user-path-created.patch
=> phosphor-network: modify patch for fixing build break

meta-nuvoton/recipes-nuvoton/ipmi/nuvoton-ipmi-oem_git.bb
Brian Ma (2):
Porting OEM GPIO function for npcm8xxx/npxm7xx
Add get pwm mode command and move fan Fn to 0x32
=> nuvoton-ipmi-oem: bump srcrev: 50d80e6...011f907

meta-nuvoton/recipes-nuvoton/ipmi/nuvoton-ipmi-oem_git.bb
Brian Ma (1):
Support read BIOS version
=> nuvoton-ipmi-oem: bump srcrev: 011f907...1fb53bf

meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-kernel/linux/linux-nuvoton/0002-kernel-scm-dts.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/flash/phosphor-software-manager/obmc-flash-host-bios@.service, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/flash/phosphor-software-manager/restore_verify_bios.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/flash/phosphor-software-manager_%.bbappend, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0001-Add-Set-BIOS-version-support.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-scm-npcm845/ipmi-bios-update/files/bios-update.sh, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-scm-npcm845/ipmi-bios-update/files/bios-verify.sh, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-scm-npcm845/ipmi-bios-update/files/config-bios.json, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-scm-npcm845/ipmi-bios-update/files/phosphor-ipmi-flash-bios-update.service, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-scm-npcm845/ipmi-bios-update/files/phosphor-ipmi-flash-bios-verify.service, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-scm-npcm845/ipmi-bios-update/ipmi-bios-update.bb, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-scm-npcm845/ipmi-bmc-update/ipmi-bmc-update.bb, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-scm-npcm845/ipmi-bmc-update/ipmi-bmc-update/bmc-verify.sh, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-scm-npcm845/ipmi-bmc-update/ipmi-bmc-update/config-bmc.json, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-scm-npcm845/ipmi-bmc-update/ipmi-bmc-update/df-mmc/bmc-verify.sh, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-scm-npcm845/ipmi-bmc-update/ipmi-bmc-update/df-mmc/config-bmc.json, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-scm-npcm845/ipmi-bmc-update/ipmi-bmc-update/df-mmc/phosphor-ipmi-flash-bmc-update.service, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-scm-npcm845/ipmi-bmc-update/ipmi-bmc-update/phosphor-ipmi-flash-bmc-verify.service, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-scm-npcm845/packagegroups/packagegroup-scm-npcm845-apps.bb
=> meta-evb: scm-npcm845: support BIOS update

meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-config.bbappend, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-config/fw.json, meta-nuvoton/recipes-nuvoton/ipmi/nuvoton-ipmi-oem_git.bb
nuvoton-ipmi-oem: bump srcrev: 1fb53bf...1fb53bf
Brian Ma (2):
Update Readme: Add BIOS version part
Support read PSU version
Add add fw.json which defined the bus and address for CPLD, SCM CPLD,
and PSU.
=> meta-scm-npcm845: add ipmi oem psu version support

meta-nuvoton/recipes-nuvoton/ipmi/nuvoton-ipmi-oem_git.bb
Brian Ma (2):
Move PWM valid value range to 0 ~ 100
Move command code fn
=> nuvoton-ipmi-oem: bump srcrev: 473db90...773f7eb

meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-config/fw.json
=> meta-evb: scm-npcm845: update fw.json

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/conf/machine/evb-npcm845.conf, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/health/phosphor-health-monitor_%.bbappend, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/health/phosphor-health-monitor_%.bbappend, meta-nuvoton/recipes-nuvoton/loadsvf/loadsvf_git.bb
Konstantin Aladyshev (2):
Set correct values for sensor min and max properties
Set unset threshold values to NaN
Patrick Williams (1):
meson: simplify dependencies
Yong Li (1):
Make health-monitor compatible with “sensor list” command
=> phosphor-health-monitor: bump srcrev: f515187...f8d7973

meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/configuration/entity-manager/aurea-hpm.json
Update missing entity ID and entity instance value
=> meta-scm-npcm845: update entity configuration

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0004-Add-SEL-add-command.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0004-Add-SEL-add-command.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend
Add patch to implement SEL add command for dynamic sensor.
=> meta-scm-npcm845: Add SEL add command suppport

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0011-Add-SEL-time-set-command.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0011-Add-SEL-time-set-command.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend
Porting SEL time set command for dynamic sensor
=> meta-scm-npcm845: Add SEL time set command suppport

meta-nuvoton/recipes-nuvoton/ipmi/nuvoton-ipmi-oem_git.bb
Brian Ma (2):
Update README, CPLD and BIOS POST code part
Add Master Phase Write-Read command support
=> nuvoton-ipmi-oem: bump srcrev: e8f09a3...29267b6

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0015-Fix-seesion-handle-duplicated.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0015-Fix-seesion-handle-duplicated.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend
Fix ipmid return session handle number may not correct issue.
=> meta-evb-npcm845: fix ipmi session handle error

meta-nuvoton/recipes-nuvoton/ipmi/nuvoton-ipmi-oem_git.bb
Brian Ma (1):
Use 0 fill up BIOS POST code to 240 bytes
=> nuvoton-ipmi-oem: bump srcrev: 29267b6...e15c65a

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0016-Add-reset-SEL.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0020-fix-percentage-type-show.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0016-Add-reset-SEL.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0020-fix-percentage-type-show.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend
Update sdr sensor unit 1 if sensor unit is percent.
=> meta-scm-npcm845: fix percentage type cannot show

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/settings/phosphor-settings-manager/time-sync.override.yml, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/settings/phosphor-settings-manager_%.bbappend, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/settings/phosphor-settings-manager/time-sync.override.yml, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/settings/phosphor-settings-manager_%.bbappend
Set time sync setting to manual as default
=> meta-scm-npcm845: set time sync setting to manual

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/interfaces/bmcweb/0001-Handle-now-allow-execption-in-account-service.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/interfaces/bmcweb/0003-Create-new-user-without-SSH-group.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend
Fix patches of bmcweb.
Modify sensor yaml path of phosphor-ipmi-host.
Test Done:
No build error. (target: olympus-nuvoton)
Boot OK.
Signed-off-by: jhkang <jhkang@nuvoton.com>
=> meta-olympus-nuvoton: fix build error after upgrading OpenBmc

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0022-add-sensor-reading-factory-support.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0022-add-sensor-reading-factory-support.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend
Add IPMI command get sensor reading factor support.
=> meta-scm-npcm845: Add IPMI sensor reading factor

meta-nuvoton/recipes-nuvoton/ipmi/nuvoton-ipmi-oem_git.bb
Brian Ma (3):
Update CPLD version format
Add Master Muxed Write-Read command support
Add default eanbled compiler option SEARCH_MUX_BUS
=> nuvoton-ipmi-oem: bump srcrev: e15c65a...a0439e4

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0023-add-oem-sel-support.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0023-add-oem-sel-support.patch, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host_%.bbappend
Add IPMI OEM SEL add/get command support.
=> meta-scm-npcm845: Add IPMI OEM SEL support

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/interfaces/bmcweb/0002-Redfish-Add-power-metrics-support.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/interfaces/bmcweb/0004-bmcweb-chassis-add-indicatorLED-support.patch
Test Done:
No build error.
Signed-off-by: jhkang <jhkang@nuvoton.com>
=> meta-olympus-nuvoton: bmcweb: fix bmcweb build error

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/sensors/dbus-sensors/0001-intrusionsensor-Add-polling-event-status-by-sysfs.patch
meta-buv-runbmc: dbus-sensors: intrusionsensor: Update patch to match new revision "bce0f038383c54dc3da515610893abeefe3be045"
=> meta-buv-runbmc: dbus-sensors: intrusionsensor: Update patch to match new revision "bce0f038383c54dc3da515610893abeefe3be045"

meta-nuvoton/recipes-nuvoton/ipmi/nuvoton-ipmi-oem_git.bb
Brian Ma (1):
Fix incorrect CPPFLAGS setting in configure.ac
=> nuvoton-ipmi-oem: bump srcrev: a0439e4...53513c4

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/ipmi/phosphor-ipmi-host/0007-dbus-sdr-storagecommands-Add-option-to-use-Clear-met.patch
Update phosphor-ipmi-host patch to fix fuzz patch warning.
=> meta-evb-npcm845: update phosphor-ipmi-host patch

meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-core/os-release/os-release.bbappend
=> meta-scm-npcm845: fix SCM version to 2.8.0-aurea

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/flash/phosphor-software-manager/support_update_uboot_with_emmc_image.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-phosphor/flash/phosphor-software-manager_%.bbappend
Add patch to support update U-Boot image on SPI flash with eMMC image.
=> meta-evb: evb-npcm845: support mmc update

meta-nuvoton/recipes-nuvoton/nuvoton-ipmi/nuvoton-ipmi-oem_git.bb
=> nuvoton-ipmi-oem: fix ipmi pwm command typo

meta-nuvoton/recipes-nuvoton/ipmi/nuvoton-ipmi-oem_git.bb
Brian Ma (1):
Add support upper case PWM sensor object path
=> nuvoton-ipmi-oem: bump srcrev: 53513c4...27d662c0

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-evb-npcm845/i3c-tools/i3c-tools_git.bb, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/console/obmc-console_%.bbappend, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-phosphor/sensors/dbus-sensors_%.bbappend, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-scm-npcm845/i3c-tools/i3c-tools_git.bb, meta-evb/meta-evb-nuvoton/meta-scm-npcm845/recipes-scm-npcm845/update-psu/update-psu_git.bb, meta-nuvoton/recipes-bsp/arm-trusted-firmware/arm-trusted-firmware.inc, meta-nuvoton/recipes-security/optee/optee-test.bb
Update recipes for porting typo, and fix licenses warnings.
=> meta-scm-npcm845: fix build break and warnings

meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/configuration/entity-manager/NUVOTON-ARBEL-EVB.json, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/configuration/entity-manager_%.bbappend, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/ipmi/phosphor-ipmi-fru/obmc/eeproms/system/chassis/bmc, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/ipmi/phosphor-ipmi-fru_%.bbappend, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/sensors/dbus-sensors/0001-hwmon-temp-add-tmp100-support.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/sensors/dbus-sensors/0002-Fansensor-get-pwm-from-other-hwmon-path.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/sensors/dbus-sensors/0003-psu-sensor-add-fan3-support.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/sensors/dbus-sensors/0004-psu-sensor-support-p2011-psu.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/sensors/dbus-sensors/0005-hwmontemp-add-adm-stbsi-support.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/sensors/dbus-sensors/0006-add-dimm-sensor.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/sensors/dbus-sensors/0007-add-nic-temp-sensor.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/sensors/dbus-sensors/0008-increase-adc-max-reading.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/sensors/dbus-sensors/0009-change-psu-sensor-name.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/sensors/dbus-sensors/0010-add-sesnor-max16550.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/sensors/dbus-sensors/0011-hwmon-temp-add-lm75-support.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/sensors/dbus-sensors/xyz.openbmc_project.dimmsensor.service, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/sensors/dbus-sensors_%.bbappend
- support sensors status on webui > Hardware status > Sensors page
- add lm75 sensor support
=> meta-evb: nuvoton: evb-npcm750: support entity manager

meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/health/phosphor-health-monitor_%.bbappend
Konstantin Aladyshev (2):
Set correct values for sensor min and max properties
Set unset threshold values to NaN
Patrick Williams (1):
meson: simplify dependencies
Yong Li (1):
Make health-monitor compatible with “sensor list” command
=> evb-npcm750: phosphor-health-monitor: bump srcrev: f515187...f8d7973

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/README.md
=> meta-evb: evb-npcm845: update README for FLM and SGPIO

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/README.md
Update npcm845 README for BMC modules.
=> meta-evb: evb-npcm845: Update README for BMC modules

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/README.md
=> meta-evb: evb-npcm845: update README for AES and SHA

meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-evb-npcm750/packagegroups/packagegroup-evb-npcm750-apps.bb, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/host/phosphor-host-postd_%.bbappend, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/state/phosphor-post-code-manager/0001-delay-serialize.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm750/recipes-phosphor/state/phosphor-post-code-manager_%.bbappend
=> meta-evb: nuvoton: evb-npcm750: support BIOS POST codes

meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-kernel/linux/linux-nuvoton/0012-stmmac-support-ncsi-kernel.patch, meta-evb/meta-evb-nuvoton/meta-evb-npcm845/recipes-kernel/linux/linux-nuvoton_%.bbappend
Update NCSI patch for kernel 5.15.
=> meta-evb: meta-evb-npcm845: Update NCSI patch for kernel 5.15

meta-nuvoton/recipes-graphics/obmc-ikvm/obmc-ikvm_%.bbappend
Change to use custom controls provided by video driver
=> meta-nuvoton: obmc-ikvm: bump srcrev fbedaee7...624e6635

meta-nuvoton/recipes-bsp/u-boot/u-boot-common-nuvoton.inc
board: nuvoton: arbel: Correct CONFIG_SYS_MEM_TOP_HIDE value
=> meta-nuvoton: u-boot-nuvoton: bump srcrev acba99d1...7e7ffaf8

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/sensors/dbus-sensors/0001-intrusionsensor-Add-polling-event-status-by-sysfs.patch
Signed-off-by: Eason Yang <yhyang2@nuvoton.com>
=> meta-buv-runbmc: update patch to fix dbus-sensors build break

meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/flash/phosphor-software-manager/0004-Add-support-for-MCU-firmware-upgrade.patch, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/flash/phosphor-software-manager/0005-Add-support-for-CPLD-firmware-upgrade.patch, meta-evb/meta-evb-nuvoton/meta-buv-runbmc/recipes-phosphor/ipmi/phosphor-ipmi-host/0001-Fix-firmware-version-missing-at-dev-tag.patch
1. Update phosphor-ipmi-host patch
2. Update phosphor-software-manager patches
Signed-off-by: Eason Yang <yhyang2@nuvoton.com>
=> meta-evb-nuvoton: buv-runbmc: Fix build break after merge code

meta-quanta/meta-olympus-nuvoton/recipes-phosphor/flash/phosphor-software-manager/restore_verify_bios.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/host/phosphor-host-postd/0001-main-add-feature-for-updating-BootProgress-and-Opera.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/interfaces/bmcweb/0002-Redfish-Add-power-metrics-support.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/interfaces/bmcweb/0003-Create-new-user-without-SSH-group.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/ipmi/phosphor-ipmi-host/0001-Fix-firmware-version-missing-at-dev-tag.patch, meta-quanta/meta-olympus-nuvoton/recipes-phosphor/network/phosphor-network/0001-Run-after-xyz-openbmc_project-user-path-created.patch
1. Update phosphor-software-manager patch
2. Update phosphor-host-postd patch
3. Update bmcweb patches
4. Update phosphor-ipmi-host patch
5. Update phosphor-network patch
Signed-off-by: Eason Yang <yhyang2@nuvoton.com>
=> meta-quanta: meta-olympus-nuvoton: Fix build break after merge code
